services:
  builder:
    build:
      dockerfile: builder.Dockerfile
      context: .
    user: ${MY_UID}:${MY_GID}
    volumes:
    - ../../:/build
    - ../tmp/data/:/data/
    - ../tmp/temp/:/temp/
